name: work
on: [push, pull_request]
jobs:
    analyze-and-test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Set up JDK 1.8
              uses: actions/setup-java@v1
              with:
                  java-version: 1.8
            - name: Setup Android SDK
              uses: android-actions/setup-android@v2
            - name: start emulator headless
              shell: bash
              run: |
                  echo "1"
                  ls /usr/local/lib/android/sdk/cmdline-tools/latest
                  echo "2"
                  ls /usr/local/lib/android/sdk/cmdline-tools/latest/bin
                  echo "3"
                  ls /usr/local/lib/android/sdk/cmdline-tools
                  /usr/local/lib/android/sdk/cmdline-tools/latest/bin/sdkmanager "platform-tools" "platforms;android-28" "emulator"
                  /usr/local/lib/android/sdk/cmdline-tools/latest/bin/sdkmanager "system-images;android-28;google_apis;x86_64"
                  echo "4"
                  ls /usr/local/lib/android/sdk/cmdline-tools/latest
                  echo "5"
                  ls /usr/local/lib/android/sdk/cmdline-tools/latest/bin
                  echo "6"
                  ls /usr/local/lib/android/sdk/cmdline-tools
                  
                  
                  
 
                
