name: MDE_Test
on: [push, pull_request]
jobs:
    analyze-and-test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: start emulator headless
              shell: bash
              run: |
                  echo "check if we can run KVM"
                  egrep -c '(vmx|svm)' /proc/cpuinfo
                  sudo kvm-ok
                  modprobe kvm_intel
                  lsmod | grep kvm
