name: work
on: [push, pull_request]
jobs:
    analyze-and-test:
        runs-on: ubuntu-latest
        steps:
            - name: start emulator headless
              shell: bash
              run: |
                sudo apt-get clean
                sudo apt-get update
                sudo apt-get upgrade -f
                sudo apt-get install procps lsof curl unzip zip libglu1 libx11-6 nxagent wget pulseaudio libnss3 lsb-release -y
                curl -s "https://get.sdkman.io" | bash
                source "$HOME/.sdkman/bin/sdkman-init.sh"
                sdk install java 8.0.322-zulu
                cd ~ && wget https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip
                ANDROID_HOME=/opt/androidsdk
                sudo mkdir -p $ANDROID_HOME
                sudo unzip sdk-tools-linux-4333796.zip -d $ANDROID_HOME
                echo "export ANDROID_HOME=$ANDROID_HOME" >> ~/.bashrc
                echo 'export SDK=$ANDROID_HOME' >> ~/.bashrc
                echo 'export PATH=$SDK/emulator:$SDK/tools:$SDK/tools/bin:$SDK/platform-tools:$PATH' >> ~/.bashrc
                source ~/.bashrc
                echo yes | /opt/androidsdk/tools/bin/sdkmanager  --licenses || if [ $? -ne '141' ]; then exit $?; fi;
                mkdir -p /root/.android && touch /root/.android/repositories.cfg
                echo "started downloading: platform-tools;platforms;android-28;emulator, please wait ...!"
                echo yes | /opt/androidsdk/tools/bin/sdkmanager  "platform-tools" "platforms;android-28" "emulator"
                echo "started downloading system-images;android-28;google_apis;x86_64,please wait ...!"
                echo yes | /opt/androidsdk/tools/bin/sdkmanager  "system-images;android-28;google_apis;x86_64"
                echo "print emulator version...!"
                /opt/androidsdk/tools/emulator -version
                /opt/androidsdk/platform-tools/adb start-server
                echo no | /opt/androidsdk/tools/bin/avdmanager create avd --force -n avd28 -k "system-images;android-28;google_apis;x86_64"
                /opt/androidsdk/tools/emulator -avd avd28 -no-audio -no-accel -no-window
                sleep 500
                /opt/androidsdk/platform-tools/adb devices
 
                  
   
                  
                  
                  
 
                
