name: work
on: [push, pull_request]
jobs:
    analyze-and-test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Set up JDK 1.8
              uses: actions/setup-java@v1
              with:
                  java-version: 1.8
            - name: start emulator headless
              shell: bash
              run: |
                cd ~ && wget https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip
                ANDROID_HOME=/opt/androidsdk
                mkdir -p $ANDROID_HOME
                unzip sdk-tools-linux-4333796.zip -d $ANDROID_HOME
                echo "export ANDROID_HOME=$ANDROID_HOME" >> ~/.bashrc
                echo 'export SDK=$ANDROID_HOME' >> ~/.bashrc
                echo 'export PATH=$SDK/emulator:$SDK/tools:$SDK/tools/bin:$PATH' >> ~/.bashrc
                source ~/.bashrc
                echo yes | /opt/androidsdk/tools/bin/sdkmanager  --licenses || if [ $? -ne '141' ]; then exit $?; fi;
                sudo mkdir -p /root/.android && touch /root/.android/repositories.cfg
                echo "started downloading: platform-tools;platforms;android-28;emulator, please wait ...!"
                /opt/androidsdk/tools/bin/sdkmanager  "platform-tools" "platforms;android-28" "emulator"
                echo "started downloading system-images;android-28;google_apis;x86_64,please wait ...!"
                /opt/androidsdk/tools/bin/sdkmanager  "system-images;android-28;google_apis;x86_64"
 
                  
   
                  
                  
                  
 
                
