name: MDE_Test
on: [push, pull_request]
jobs:
    analyze-and-test:
        runs-on: ubuntu-latest
        steps:
             - name: checkout
               uses: actions/checkout@v3
             - name: run tests
               uses: reactivecircus/android-emulator-runner@v2
               with:
                 api-level: 29
                 script: chmod +x gradlew && ./gradlew connectedCheck
             - name: start emulator headless-
               shell: bash
               run: |
                  set -x
                  ls /home/runner/work/codewars_challenges/codewars_challenges
                  /usr/local/lib/android/sdk/platform-tools/adb devices
                  /usr/local/lib/android/sdk/platform-tools/adb shell pm list packages
                  /usr/local/lib/android/sdk/platform-tools/adb install /home/runner/work/codewars_challenges/codewars_challenges/apps/app-x86_64-release.apk

        
