name: manuall workflow
on: [push, pull_request]
jobs:
    analyze-and-test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-java@v1
              with:
                  java-version: '11.x'
            - name: Set up JDK 1.8
              uses: actions/setup-java@v1
              with:
                  java-version: 1.8

            - name: Setup Android SDK
              uses: android-actions/setup-android@v2
            - name: start emulator headless
              shell: bash
              run: |
               echo $ANDROID_HOME
               sdkmanager "platform-tools" "platforms;android-28" "emulator"
               sdkmanager "system-images;android-28;google_apis;x86_64"
               echo "print emulator version...!"
               emulator -version
               adb start-server
               echo no | avdmanager create avd --force -n avd28 -k "system-images;android-28;google_apis;x86_64"
               emulator -avd avd28 -no-audio -no-accel -no-window
               adb devices
    
